### ISSUE TITLE
`here::here` 和 `child`

### ISSUE THREAD

**Issue by JiaxiangBU** [JiaxiangBU/learn_rmd#12]
## todos

- [x] 整理笔记
- [x] GitHub 上没有。 https://github.com/r-lib/here/issues?utf8=%E2%9C%93&q=github+pages
- [x] 这个是相关的 https://yihui.name/knitr/objects/
- [x] child Rmd relative path https://github.com/rstudio/rmarkdown/issues?utf8=%E2%9C%93&q=relative+path+child
- [x] 用相对路径？ https://github.com/rstudio/rmarkdown/issues/1152
- [x] `knit_child` 可能会解决这个问题，看了 help 文档。

**Comment by JiaxiangBU** [comment]
## 测试相对路径

使用 `here::here` 主要就是怕文件路径变了，需要批量修改。但是就不能使用 tab 联想了。

```r
include_graphics("../../refs/git-address.png")
```

导致相对路径直接应用到了 parent document，图片路径显示为 https://jiaxiangbu.github.io/refs/git-address.png

- [x] both  `here::here` 呢？ 那么产生 `about:blank`

这里产生一个问题，如果两个地方都使用了相对路径，导入过来的时候会不会报错。
肯定会的，因为只是把文件 copy 过来。

**Comment by JiaxiangBU** [comment]
查看了部分回答，child 调用的时候不会把相对路径进行转置，至少在 code 方面，因此调用的时候需要小心。能不能所有文档都设置一个默认路径呢？

* [Optimizing R Markdown workflow - reusing R Markdown chunks with parameters? - R Markdown - RStudio Community](https://community.rstudio.com/t/optimizing-r-markdown-workflow-reusing-r-markdown-chunks-with-parameters/14640/4)

阅读 here GitHub 估计有答案。

https://here.r-lib.org/news/index.html 没有。

`setwd` 或者 `set_here` 后，想问 tab 等会有变化吗？

* [Set Working Directory in Rstudio](https://eranraviv.com/r-tips-and-tricks-working-directory/) 如果是直接传代码过来，我的感觉是各种路径问题，应该从文档 knit 思路上修改，也就是 tab 提示是，要是被调用的位置。或者说默认是项目地址，这样好让不同 learning-notes 去调用。

有可能是 workflowr 进行了干扰。
因为输出的路径是 `file:///D:/work/learn_git/output/refs/git-address.png`
那是因为文件在 `output` 路径。我目前的问题是感觉孤军奋战好难。

所以这不是 child 这个功能的问题，只调用了文档。
问题是需要每个问题识别自己的路径是项目路径。

**Comment by JiaxiangBU** [comment]
<kbd>Knit Directory</kbd> 选择项目地址，是可以 run 的，但是不能 knit，估计这个路径还需要设计一下。

另外一个是 tab **不能使用**。

**Comment by JiaxiangBU** [comment]
## double here 的问题

child 无论用相对路径还是 here 路径，我的解决是图片都是 work 的，因为 child 只是一个传文件的功能。
那么最后就出在这个路径对于这个 gitbook 来说，怎么识别了。
为什么识别不对呢？需要看下 HTML 文件。

`<img src="D:/work/learn_git/refs/git-address.png" alt="复制项目地址" width="608" />` 路径直接被写死了。

在线上时，`view-source:https://jiaxiangbu.github.io/learn_git/output/git-github-gitlab-learning-notes.html#section-5`

```html

<p>打开 Git Bash，定位到项目想要下载的位置，如桌面。</p>
--
  | <pre class="sourceCode r"><code class="sourceCode r"><span class="kw">include_graphics</span>(here<span class="op">::</span><span class="kw">here</span>(<span class="st">&quot;refs/git-address.png&quot;</span>))</code></pre>
  | <div class="figure"><span id="fig:unnamed-chunk-24"></span>
  | <img src="D:/work/learn_git/refs/git-address.png" alt="复制项目地址" width="608" />
```

这就很尴尬了，图片位置还是绝对路径。

因此问题变成在放到 GitHub 时，这个图片怎么写到服务器上，这里的知识需要结合 blogdown 和 bookdown 解决。

bookdown 不让再设置默认地址了。

**Comment by JiaxiangBU** [comment]
可能相关的问题 https://github.com/r-lib/here/issues/31

**Comment by JiaxiangBU** [comment]
> here::here() works like file.path(), but where the path root is implicitly set to “the path to the top-level of my current project”. See The Fine Print for the underlying heuristics. If they don’t suit, use the more powerful package rprojroot directly. Both here and rprojroot are written by Kirill Müller and are available on CRAN.
https://github.com/jennybc/here_here#the-fine-print

可能是一个解决方案，替换包。

看完了没觉得啥， https://rprojroot.r-lib.org/articles/rprojroot.html

**Comment by JiaxiangBU** [comment]
我感觉关键问题是要设置一个访问地址是 GitHub Pages 这个，而非被 here::here 影响。
实在不行在生成的 HTML 文件上直接正则化替换，直接替换成相对路径。

```
./refs/click-board.png
```

这个没错，但是如果文件是在其他文件夹呢？这个需要相对路径处理好。

问题解决了，思考下函数怎么跑。

`".."` 这个是一个问题，这么自动识别呢？

设置参数 `path_to_root = ".."`
写一个包 https://github.com/JiaxiangBU/add2here
